### ISSUE TITLE
Display name for compose metrics is set to formula instead of name

### ISSUE THREAD

**Issue by jankatins** [mara/mara-metabase#8]
Currently a composed metric gets the formula as display name but simple metrics default to the name as defined in the mara-schema:

https://github.com/mara/mara-metabase/blob/master/mara_metabase/metadata.py#L69
```
     'definition': {'source-table': table['id'],
                                         'aggregation': [
                                             metric_definition(_metric, table)
                                             if isinstance(_metric, SimpleMetric)
                                             else ['aggregation-options',
                                                   metric_definition(_metric, table),
                                                   {'display-name': _metric.display_formula()}
                                                   ]
                                         ]},
```

This means if you explore the dataset in metabase and summarize, you will have names as in the data dictionary for simply metrics but the formulas for composed metrics in parts of the graph. E.g. here the headline has the names, but the legend has the formula

![image](https://user-images.githubusercontent.com/890156/99801675-b7fd6f00-2b36-11eb-88c2-7cd7098da559.png)

Is that intended? If yes: would it be ok to make this configureable (without me vendoring /patching the whole metadata sync function?)

**Comment by martin-loetzsch** [comment]
Ideally the display name would be the name of the composed metric. Is that possible?

**Comment by jankatins** [comment]
Yes, it's actually specifically different right now, having the metric name as display name is simplifying the if-else block by removing one part. So i thought it was done like this on purpose...

**Comment by jankatins** [comment]
#9 has a patch to make it the UI stuff patchable
